#server config
server:
  port: 8762            #服务端口号

spring:
  application:
    name: eureka-server2          #服务名

eureka:
  server:
    enable-self-preservation: false           #阻止自我注册(不阻止)
    eviction-interval-timer-in-ms: 60000    #清理(失效服务)间隔
  client:
    fetch-registry: false            #获取注册
    service-url:
      defaultZone: http://localhost:8761/eureka/   #注册中心的地址
