
server:
  port: 10003             #消费者服务端口

spring:
  application:
    name: eureka-consumer2    #消费者服务名

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka    #消费服务访问的地址