
server:
  port: 10001

spring:
  application:
    name: eureka-provider    #声明服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myrbac
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  #注册中心的地址
